# Gunakan base image Python
FROM python:3.10-slim

# Set workdir
WORKDIR /app

# # Copy requirements.txt dari root project ke container
# COPY ../requirements.txt /tmp/requirements.txt

# # Install dependencies
# RUN pip install --no-cache-dir -r /tmp/requirements.txt

# # Copy semua file project
# COPY . .
